#!/usr/bin/env bash

set -ueo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

if [[ -n "$BUILDKITE_PLUGIN_DAGGER_VERSION" ]]; then
  export DAGGER_VERSION="$BUILDKITE_PLUGIN_DAGGER_VERSION"
  export BIN_DIR=${BIN_DIR:-/usr/bin}
  current_version=""
  
  if which dagger > /dev/null; then
    current_version=$(dagger version | cut -d' ' -f2)
  fi

  if [[ "$current_version" != "$DAGGER_VERSION" ]]; then
    echo "Installing dagger version $DAGGER_VERSION"

    bash $DIR/../install.sh
  else
    echo "Using dagger version $current_version"
  fi
fi

dagger call --progress plain -m "$BUILDKITE_PLUGIN_DAGGER_MODULE" $BUILDKITE_PLUGIN_DAGGER_CALL
